from TrenoRepository import TrenoRepository

if __name__ == '__main__':
    repo = TrenoRepository()
    treno = repo.cercaTreno("9434")
    andamento = repo.andamentoTreno(treno)
    tratte = repo.tratteTreno(treno)
    statistiche = repo.statistiche()
    # stazioni = repo.elencoStazioni()
    news = repo.news()
    partenze = repo.partenze("S02581")
    arrivi = repo.arrivi("S02581")
    regioneStazione = repo.regioneStazione("S02581")

    print('treno')
    print(treno)
    print('news')
    print(news)
    print('andamento')
    print(andamento)
    print('tratte')
    print(tratte)
    print('statistiche')
    print(statistiche)
    print('partenze')
    print(partenze)
    print('arrivi')
    print(arrivi)
    print('regioneStazione')
    print(regioneStazione)
